# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='name',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
