# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0007_auto_20170928_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='short_description',
            field=models.CharField(max_length=128),
        ),
    ]
