# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0009_auto_20170928_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
