# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0010_campground_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campground',
            old_name='price',
            new_name='price_per_night',
        ),
    ]
