# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0012_auto_20170928_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='rating',
            field=models.IntegerField(choices=[('Bad (1)', 1), ('Ok (2)', 2), ('Average (3)', 3), ('Good (4)', 4), ('Great (5)', 5)], default=5),
        ),
    ]
