# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campgrounds', '0013_campground_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('rating', models.IntegerField(choices=[('Bad (1)', 1), ('Ok (2)', 2), ('Average (3)', 3), ('Good (4)', 4), ('Great (5)', 5)], default=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='campground',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='campground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='campgrounds.Campground'),
        ),
    ]
