# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0014_auto_20170928_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Bad (1)'), (2, 'Ok (2)'), (3, 'Average (3)'), (4, 'Good (4)'), (5, 'Great (5)')], default=5),
        ),
    ]
