# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 21:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0015_auto_20170929_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 21, 59, 36, 867191, tzinfo=utc)),
        ),
    ]
