# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 19:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0016_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='city',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AddField(
            model_name='campground',
            name='province',
            field=models.CharField(choices=[('British Columbia', 'BC')], default='BC', max_length=56),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='campground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='campgrounds.Campground'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 5, 19, 39, 41, 277586, tzinfo=utc)),
        ),
    ]
