# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 20:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0022_auto_20171013_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 20, 31, 13, 168280, tzinfo=utc)),
        ),
    ]
