# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 20:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0023_auto_20171013_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='province',
            field=models.CharField(choices=[('British Columbia', 'BC'), ('Alberta', 'AB'), ('Saskatchewan', 'SK'), ('Manitoba', 'MB'), ('Ontario', 'ON'), ('Quebec', 'QC'), ('New Brunswick', 'NB'), ('Newfoundland and Labrador', 'NL'), ('Nova Scotia', 'NS'), ('Prince Edward Island', 'PEI'), ('Yukon', 'YK'), ('Northwest Territories', 'NT'), ('Nunavut', 'NU')], default='BC', max_length=56),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 20, 20, 35, 931480, tzinfo=utc)),
        ),
    ]
